package com.heagle.monitor.base.model;

import java.io.Serializable;
import java.util.Date;

public class JngSysOnlineModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.ONLINE_JNLS_NO
     *
     * @mbggenerated
     */
    private String onlineJnlsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.SESSION_ID
     *
     * @mbggenerated
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.OPER_NO
     *
     * @mbggenerated
     */
    private String operNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.ONLINE_IP
     *
     * @mbggenerated
     */
    private String onlineIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.ONLINE_TYPE
     *
     * @mbggenerated
     */
    private String onlineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.TERMINAL_TYPE
     *
     * @mbggenerated
     */
    private String terminalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.ACCESS_TYPE
     *
     * @mbggenerated
     */
    private String accessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.SSO_TOKEN
     *
     * @mbggenerated
     */
    private String ssoToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.SYSTEM_TOKEN
     *
     * @mbggenerated
     */
    private String systemToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.ONLINE_STATUS
     *
     * @mbggenerated
     */
    private String onlineStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JNG_SYS_ONLINE_LIST.REG_DATE
     *
     * @mbggenerated
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_JNLS_NO
     *
     * @return the value of JNG_SYS_ONLINE_LIST.ONLINE_JNLS_NO
     *
     * @mbggenerated
     */
    public String getOnlineJnlsNo() {
        return onlineJnlsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_JNLS_NO
     *
     * @param onlineJnlsNo the value for JNG_SYS_ONLINE_LIST.ONLINE_JNLS_NO
     *
     * @mbggenerated
     */
    public void setOnlineJnlsNo(String onlineJnlsNo) {
        this.onlineJnlsNo = onlineJnlsNo == null ? null : onlineJnlsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.SESSION_ID
     *
     * @return the value of JNG_SYS_ONLINE_LIST.SESSION_ID
     *
     * @mbggenerated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.SESSION_ID
     *
     * @param sessionId the value for JNG_SYS_ONLINE_LIST.SESSION_ID
     *
     * @mbggenerated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.OPER_NO
     *
     * @return the value of JNG_SYS_ONLINE_LIST.OPER_NO
     *
     * @mbggenerated
     */
    public String getOperNo() {
        return operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.OPER_NO
     *
     * @param operNo the value for JNG_SYS_ONLINE_LIST.OPER_NO
     *
     * @mbggenerated
     */
    public void setOperNo(String operNo) {
        this.operNo = operNo == null ? null : operNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_IP
     *
     * @return the value of JNG_SYS_ONLINE_LIST.ONLINE_IP
     *
     * @mbggenerated
     */
    public String getOnlineIp() {
        return onlineIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_IP
     *
     * @param onlineIp the value for JNG_SYS_ONLINE_LIST.ONLINE_IP
     *
     * @mbggenerated
     */
    public void setOnlineIp(String onlineIp) {
        this.onlineIp = onlineIp == null ? null : onlineIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_TYPE
     *
     * @return the value of JNG_SYS_ONLINE_LIST.ONLINE_TYPE
     *
     * @mbggenerated
     */
    public String getOnlineType() {
        return onlineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_TYPE
     *
     * @param onlineType the value for JNG_SYS_ONLINE_LIST.ONLINE_TYPE
     *
     * @mbggenerated
     */
    public void setOnlineType(String onlineType) {
        this.onlineType = onlineType == null ? null : onlineType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.TERMINAL_TYPE
     *
     * @return the value of JNG_SYS_ONLINE_LIST.TERMINAL_TYPE
     *
     * @mbggenerated
     */
    public String getTerminalType() {
        return terminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.TERMINAL_TYPE
     *
     * @param terminalType the value for JNG_SYS_ONLINE_LIST.TERMINAL_TYPE
     *
     * @mbggenerated
     */
    public void setTerminalType(String terminalType) {
        this.terminalType = terminalType == null ? null : terminalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.ACCESS_TYPE
     *
     * @return the value of JNG_SYS_ONLINE_LIST.ACCESS_TYPE
     *
     * @mbggenerated
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.ACCESS_TYPE
     *
     * @param accessType the value for JNG_SYS_ONLINE_LIST.ACCESS_TYPE
     *
     * @mbggenerated
     */
    public void setAccessType(String accessType) {
        this.accessType = accessType == null ? null : accessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.SSO_TOKEN
     *
     * @return the value of JNG_SYS_ONLINE_LIST.SSO_TOKEN
     *
     * @mbggenerated
     */
    public String getSsoToken() {
        return ssoToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.SSO_TOKEN
     *
     * @param ssoToken the value for JNG_SYS_ONLINE_LIST.SSO_TOKEN
     *
     * @mbggenerated
     */
    public void setSsoToken(String ssoToken) {
        this.ssoToken = ssoToken == null ? null : ssoToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.SYSTEM_TOKEN
     *
     * @return the value of JNG_SYS_ONLINE_LIST.SYSTEM_TOKEN
     *
     * @mbggenerated
     */
    public String getSystemToken() {
        return systemToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.SYSTEM_TOKEN
     *
     * @param systemToken the value for JNG_SYS_ONLINE_LIST.SYSTEM_TOKEN
     *
     * @mbggenerated
     */
    public void setSystemToken(String systemToken) {
        this.systemToken = systemToken == null ? null : systemToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_STATUS
     *
     * @return the value of JNG_SYS_ONLINE_LIST.ONLINE_STATUS
     *
     * @mbggenerated
     */
    public String getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.ONLINE_STATUS
     *
     * @param onlineStatus the value for JNG_SYS_ONLINE_LIST.ONLINE_STATUS
     *
     * @mbggenerated
     */
    public void setOnlineStatus(String onlineStatus) {
        this.onlineStatus = onlineStatus == null ? null : onlineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JNG_SYS_ONLINE_LIST.REG_DATE
     *
     * @return the value of JNG_SYS_ONLINE_LIST.REG_DATE
     *
     * @mbggenerated
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JNG_SYS_ONLINE_LIST.REG_DATE
     *
     * @param regDate the value for JNG_SYS_ONLINE_LIST.REG_DATE
     *
     * @mbggenerated
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
}