package com.heagle.monitor.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class JngSysTransModelCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public JngSysTransModelCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.util.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTransJnlsNoIsNull() {
            addCriterion("jngSysTrans.TRANS_JNLS_NO is null");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoIsNotNull() {
            addCriterion("jngSysTrans.TRANS_JNLS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoEqualTo(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO =", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoNotEqualTo(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO <>", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoGreaterThan(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO >", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO >=", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoLessThan(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO <", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO <=", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoLike(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO like", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoNotLike(String value) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO not like", value, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoIn(List<String> values) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO in", values, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoNotIn(List<String> values) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO not in", values, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoBetween(String value1, String value2) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO between", value1, value2, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andTransJnlsNoNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.TRANS_JNLS_NO not between", value1, value2, "transJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoIsNull() {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO is null");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoIsNotNull() {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoEqualTo(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO =", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotEqualTo(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO <>", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoGreaterThan(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO >", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO >=", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoLessThan(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO <", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO <=", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoLike(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO like", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotLike(String value) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO not like", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoIn(List<String> values) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO in", values, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotIn(List<String> values) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO not in", values, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoBetween(String value1, String value2) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO between", value1, value2, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.ONLINE_JNLS_NO not between", value1, value2, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("jngSysTrans.SESSION_ID is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("jngSysTrans.SESSION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("jngSysTrans.SESSION_ID =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("jngSysTrans.SESSION_ID <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("jngSysTrans.SESSION_ID >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.SESSION_ID >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("jngSysTrans.SESSION_ID <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.SESSION_ID <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("jngSysTrans.SESSION_ID like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("jngSysTrans.SESSION_ID not like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("jngSysTrans.SESSION_ID in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("jngSysTrans.SESSION_ID not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("jngSysTrans.SESSION_ID between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.SESSION_ID not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andOperNoIsNull() {
            addCriterion("jngSysTrans.OPER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOperNoIsNotNull() {
            addCriterion("jngSysTrans.OPER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOperNoEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_NO =", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_NO <>", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoGreaterThan(String value) {
            addCriterion("jngSysTrans.OPER_NO >", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_NO >=", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoLessThan(String value) {
            addCriterion("jngSysTrans.OPER_NO <", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_NO <=", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoLike(String value) {
            addCriterion("jngSysTrans.OPER_NO like", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotLike(String value) {
            addCriterion("jngSysTrans.OPER_NO not like", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoIn(List<String> values) {
            addCriterion("jngSysTrans.OPER_NO in", values, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotIn(List<String> values) {
            addCriterion("jngSysTrans.OPER_NO not in", values, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoBetween(String value1, String value2) {
            addCriterion("jngSysTrans.OPER_NO between", value1, value2, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.OPER_NO not between", value1, value2, "operNo");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNull() {
            addCriterion("jngSysTrans.REQUEST_URL is null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNotNull() {
            addCriterion("jngSysTrans.REQUEST_URL is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_URL =", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_URL <>", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThan(String value) {
            addCriterion("jngSysTrans.REQUEST_URL >", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_URL >=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThan(String value) {
            addCriterion("jngSysTrans.REQUEST_URL <", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_URL <=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLike(String value) {
            addCriterion("jngSysTrans.REQUEST_URL like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotLike(String value) {
            addCriterion("jngSysTrans.REQUEST_URL not like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIn(List<String> values) {
            addCriterion("jngSysTrans.REQUEST_URL in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotIn(List<String> values) {
            addCriterion("jngSysTrans.REQUEST_URL not in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlBetween(String value1, String value2) {
            addCriterion("jngSysTrans.REQUEST_URL between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.REQUEST_URL not between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andProcessCodeIsNull() {
            addCriterion("jngSysTrans.PROCESS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProcessCodeIsNotNull() {
            addCriterion("jngSysTrans.PROCESS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProcessCodeEqualTo(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE =", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeNotEqualTo(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE <>", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeGreaterThan(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE >", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE >=", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeLessThan(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE <", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE <=", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeLike(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE like", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeNotLike(String value) {
            addCriterion("jngSysTrans.PROCESS_CODE not like", value, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeIn(List<String> values) {
            addCriterion("jngSysTrans.PROCESS_CODE in", values, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeNotIn(List<String> values) {
            addCriterion("jngSysTrans.PROCESS_CODE not in", values, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeBetween(String value1, String value2) {
            addCriterion("jngSysTrans.PROCESS_CODE between", value1, value2, "processCode");
            return (Criteria) this;
        }

        public Criteria andProcessCodeNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.PROCESS_CODE not between", value1, value2, "processCode");
            return (Criteria) this;
        }

        public Criteria andRequestContentIsNull() {
            addCriterion("jngSysTrans.REQUEST_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andRequestContentIsNotNull() {
            addCriterion("jngSysTrans.REQUEST_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andRequestContentEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT =", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentNotEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT <>", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentGreaterThan(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT >", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT >=", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentLessThan(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT <", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT <=", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentLike(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT like", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentNotLike(String value) {
            addCriterion("jngSysTrans.REQUEST_CONTENT not like", value, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentIn(List<String> values) {
            addCriterion("jngSysTrans.REQUEST_CONTENT in", values, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentNotIn(List<String> values) {
            addCriterion("jngSysTrans.REQUEST_CONTENT not in", values, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentBetween(String value1, String value2) {
            addCriterion("jngSysTrans.REQUEST_CONTENT between", value1, value2, "requestContent");
            return (Criteria) this;
        }

        public Criteria andRequestContentNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.REQUEST_CONTENT not between", value1, value2, "requestContent");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeIsNull() {
            addCriterion("jngSysTrans.TRANS_BEGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeIsNotNull() {
            addCriterion("jngSysTrans.TRANS_BEGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME =", value, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME <>", value, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME >", value, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME >=", value, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeLessThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME <", value, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME <=", value, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME in", values, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME not in", values, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME between", value1, value2, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransBeginTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_BEGIN_TIME not between", value1, value2, "transBeginTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeIsNull() {
            addCriterion("jngSysTrans.TRANS_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeIsNotNull() {
            addCriterion("jngSysTrans.TRANS_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME =", value, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME <>", value, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME >", value, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME >=", value, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeLessThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME <", value, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME <=", value, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME in", values, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME not in", values, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME between", value1, value2, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andTransEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.TRANS_END_TIME not between", value1, value2, "transEndTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusIsNull() {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusIsNotNull() {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS =", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusNotEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS <>", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusGreaterThan(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS >", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS >=", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusLessThan(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS <", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS <=", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusLike(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS like", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusNotLike(String value) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS not like", value, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusIn(List<String> values) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS in", values, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusNotIn(List<String> values) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS not in", values, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusBetween(String value1, String value2) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS between", value1, value2, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckStatusNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.OPER_CHECK_STATUS not between", value1, value2, "operCheckStatus");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeIsNull() {
            addCriterion("jngSysTrans.OPER_CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeIsNotNull() {
            addCriterion("jngSysTrans.OPER_CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME =", value, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME <>", value, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME >", value, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME >=", value, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeLessThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME <", value, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME <=", value, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME in", values, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME not in", values, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME between", value1, value2, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andOperCheckTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.OPER_CHECK_TIME not between", value1, value2, "operCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusIsNull() {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusIsNotNull() {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS =", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusNotEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS <>", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusGreaterThan(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS >", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS >=", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusLessThan(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS <", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS <=", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusLike(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS like", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusNotLike(String value) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS not like", value, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusIn(List<String> values) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS in", values, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusNotIn(List<String> values) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS not in", values, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusBetween(String value1, String value2) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS between", value1, value2, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckStatusNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.REQUEST_CHECK_STATUS not between", value1, value2, "requestCheckStatus");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeIsNull() {
            addCriterion("jngSysTrans.REQUEST_CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeIsNotNull() {
            addCriterion("jngSysTrans.REQUEST_CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME =", value, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME <>", value, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME >", value, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME >=", value, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeLessThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME <", value, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME <=", value, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME in", values, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME not in", values, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME between", value1, value2, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andRequestCheckTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.REQUEST_CHECK_TIME not between", value1, value2, "requestCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusIsNull() {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusIsNotNull() {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusEqualTo(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS =", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusNotEqualTo(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS <>", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusGreaterThan(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS >", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS >=", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusLessThan(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS <", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS <=", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusLike(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS like", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusNotLike(String value) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS not like", value, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusIn(List<String> values) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS in", values, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusNotIn(List<String> values) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS not in", values, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusBetween(String value1, String value2) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS between", value1, value2, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckStatusNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.AUTH_CHECK_STATUS not between", value1, value2, "authCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeIsNull() {
            addCriterion("jngSysTrans.AUTH_CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeIsNotNull() {
            addCriterion("jngSysTrans.AUTH_CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME =", value, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME <>", value, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME >", value, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME >=", value, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeLessThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME <", value, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME <=", value, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME in", values, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME not in", values, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME between", value1, value2, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andAuthCheckTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.AUTH_CHECK_TIME not between", value1, value2, "authCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusIsNull() {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusIsNotNull() {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusEqualTo(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS =", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusNotEqualTo(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS <>", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusGreaterThan(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS >", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS >=", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusLessThan(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS <", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS <=", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusLike(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS like", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusNotLike(String value) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS not like", value, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusIn(List<String> values) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS in", values, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusNotIn(List<String> values) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS not in", values, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusBetween(String value1, String value2) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS between", value1, value2, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckStatusNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.JSON_CHECK_STATUS not between", value1, value2, "jsonCheckStatus");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeIsNull() {
            addCriterion("jngSysTrans.JSON_CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeIsNotNull() {
            addCriterion("jngSysTrans.JSON_CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME =", value, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME <>", value, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME >", value, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME >=", value, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeLessThan(Date value) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME <", value, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME <=", value, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME in", values, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME not in", values, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME between", value1, value2, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andJsonCheckTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysTrans.JSON_CHECK_TIME not between", value1, value2, "jsonCheckTime");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNull() {
            addCriterion("jngSysTrans.TRANS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNotNull() {
            addCriterion("jngSysTrans.TRANS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTransStatusEqualTo(Long value) {
            addCriterion("jngSysTrans.TRANS_STATUS =", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotEqualTo(Long value) {
            addCriterion("jngSysTrans.TRANS_STATUS <>", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThan(Long value) {
            addCriterion("jngSysTrans.TRANS_STATUS >", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThanOrEqualTo(Long value) {
            addCriterion("jngSysTrans.TRANS_STATUS >=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThan(Long value) {
            addCriterion("jngSysTrans.TRANS_STATUS <", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThanOrEqualTo(Long value) {
            addCriterion("jngSysTrans.TRANS_STATUS <=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusIn(List<Long> values) {
            addCriterion("jngSysTrans.TRANS_STATUS in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotIn(List<Long> values) {
            addCriterion("jngSysTrans.TRANS_STATUS not in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusBetween(Long value1, Long value2) {
            addCriterion("jngSysTrans.TRANS_STATUS between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotBetween(Long value1, Long value2) {
            addCriterion("jngSysTrans.TRANS_STATUS not between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andErrorMessIsNull() {
            addCriterion("jngSysTrans.ERROR_MESS is null");
            return (Criteria) this;
        }

        public Criteria andErrorMessIsNotNull() {
            addCriterion("jngSysTrans.ERROR_MESS is not null");
            return (Criteria) this;
        }

        public Criteria andErrorMessEqualTo(String value) {
            addCriterion("jngSysTrans.ERROR_MESS =", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessNotEqualTo(String value) {
            addCriterion("jngSysTrans.ERROR_MESS <>", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessGreaterThan(String value) {
            addCriterion("jngSysTrans.ERROR_MESS >", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.ERROR_MESS >=", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessLessThan(String value) {
            addCriterion("jngSysTrans.ERROR_MESS <", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.ERROR_MESS <=", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessLike(String value) {
            addCriterion("jngSysTrans.ERROR_MESS like", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessNotLike(String value) {
            addCriterion("jngSysTrans.ERROR_MESS not like", value, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessIn(List<String> values) {
            addCriterion("jngSysTrans.ERROR_MESS in", values, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessNotIn(List<String> values) {
            addCriterion("jngSysTrans.ERROR_MESS not in", values, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessBetween(String value1, String value2) {
            addCriterion("jngSysTrans.ERROR_MESS between", value1, value2, "errorMess");
            return (Criteria) this;
        }

        public Criteria andErrorMessNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.ERROR_MESS not between", value1, value2, "errorMess");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoIsNull() {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO is null");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoIsNotNull() {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoEqualTo(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO =", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoNotEqualTo(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO <>", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoGreaterThan(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO >", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO >=", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoLessThan(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO <", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoLessThanOrEqualTo(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO <=", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoLike(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO like", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoNotLike(String value) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO not like", value, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoIn(List<String> values) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO in", values, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoNotIn(List<String> values) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO not in", values, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoBetween(String value1, String value2) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO between", value1, value2, "appTransJnlsNo");
            return (Criteria) this;
        }

        public Criteria andAppTransJnlsNoNotBetween(String value1, String value2) {
            addCriterion("jngSysTrans.APP_TRANS_JNLS_NO not between", value1, value2, "appTransJnlsNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JNG_SYS_TRANS_LIST
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}