package com.monitor.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class JngSysOnlineModelCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public JngSysOnlineModelCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOnlineJnlsNoIsNull() {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO is null");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoIsNotNull() {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO =", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO <>", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoGreaterThan(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO >", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO >=", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoLessThan(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO <", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO <=", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoLike(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO like", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotLike(String value) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO not like", value, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO in", values, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO not in", values, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO between", value1, value2, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andOnlineJnlsNoNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_JNLS_NO not between", value1, value2, "onlineJnlsNo");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("jngSysOnline.SESSION_ID is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("jngSysOnline.SESSION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("jngSysOnline.SESSION_ID =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("jngSysOnline.SESSION_ID <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("jngSysOnline.SESSION_ID >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.SESSION_ID >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("jngSysOnline.SESSION_ID <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.SESSION_ID <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("jngSysOnline.SESSION_ID like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("jngSysOnline.SESSION_ID not like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("jngSysOnline.SESSION_ID in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("jngSysOnline.SESSION_ID not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("jngSysOnline.SESSION_ID between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.SESSION_ID not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andOperNoIsNull() {
            addCriterion("jngSysOnline.OPER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOperNoIsNotNull() {
            addCriterion("jngSysOnline.OPER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOperNoEqualTo(String value) {
            addCriterion("jngSysOnline.OPER_NO =", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotEqualTo(String value) {
            addCriterion("jngSysOnline.OPER_NO <>", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoGreaterThan(String value) {
            addCriterion("jngSysOnline.OPER_NO >", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.OPER_NO >=", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoLessThan(String value) {
            addCriterion("jngSysOnline.OPER_NO <", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.OPER_NO <=", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoLike(String value) {
            addCriterion("jngSysOnline.OPER_NO like", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotLike(String value) {
            addCriterion("jngSysOnline.OPER_NO not like", value, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoIn(List<String> values) {
            addCriterion("jngSysOnline.OPER_NO in", values, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotIn(List<String> values) {
            addCriterion("jngSysOnline.OPER_NO not in", values, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoBetween(String value1, String value2) {
            addCriterion("jngSysOnline.OPER_NO between", value1, value2, "operNo");
            return (Criteria) this;
        }

        public Criteria andOperNoNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.OPER_NO not between", value1, value2, "operNo");
            return (Criteria) this;
        }

        public Criteria andOnlineIpIsNull() {
            addCriterion("jngSysOnline.ONLINE_IP is null");
            return (Criteria) this;
        }

        public Criteria andOnlineIpIsNotNull() {
            addCriterion("jngSysOnline.ONLINE_IP is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineIpEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_IP =", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpNotEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_IP <>", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpGreaterThan(String value) {
            addCriterion("jngSysOnline.ONLINE_IP >", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_IP >=", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpLessThan(String value) {
            addCriterion("jngSysOnline.ONLINE_IP <", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_IP <=", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpLike(String value) {
            addCriterion("jngSysOnline.ONLINE_IP like", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpNotLike(String value) {
            addCriterion("jngSysOnline.ONLINE_IP not like", value, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_IP in", values, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpNotIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_IP not in", values, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_IP between", value1, value2, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineIpNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_IP not between", value1, value2, "onlineIp");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeIsNull() {
            addCriterion("jngSysOnline.ONLINE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeIsNotNull() {
            addCriterion("jngSysOnline.ONLINE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE =", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeNotEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE <>", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeGreaterThan(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE >", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE >=", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeLessThan(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE <", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE <=", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeLike(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE like", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeNotLike(String value) {
            addCriterion("jngSysOnline.ONLINE_TYPE not like", value, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_TYPE in", values, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeNotIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_TYPE not in", values, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_TYPE between", value1, value2, "onlineType");
            return (Criteria) this;
        }

        public Criteria andOnlineTypeNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_TYPE not between", value1, value2, "onlineType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeIsNull() {
            addCriterion("jngSysOnline.TERMINAL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeIsNotNull() {
            addCriterion("jngSysOnline.TERMINAL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeEqualTo(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE =", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeNotEqualTo(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE <>", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeGreaterThan(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE >", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE >=", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeLessThan(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE <", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE <=", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeLike(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE like", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeNotLike(String value) {
            addCriterion("jngSysOnline.TERMINAL_TYPE not like", value, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeIn(List<String> values) {
            addCriterion("jngSysOnline.TERMINAL_TYPE in", values, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeNotIn(List<String> values) {
            addCriterion("jngSysOnline.TERMINAL_TYPE not in", values, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeBetween(String value1, String value2) {
            addCriterion("jngSysOnline.TERMINAL_TYPE between", value1, value2, "terminalType");
            return (Criteria) this;
        }

        public Criteria andTerminalTypeNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.TERMINAL_TYPE not between", value1, value2, "terminalType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeIsNull() {
            addCriterion("jngSysOnline.ACCESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAccessTypeIsNotNull() {
            addCriterion("jngSysOnline.ACCESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTypeEqualTo(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE =", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeNotEqualTo(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE <>", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeGreaterThan(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE >", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE >=", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeLessThan(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE <", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE <=", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeLike(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE like", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeNotLike(String value) {
            addCriterion("jngSysOnline.ACCESS_TYPE not like", value, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeIn(List<String> values) {
            addCriterion("jngSysOnline.ACCESS_TYPE in", values, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeNotIn(List<String> values) {
            addCriterion("jngSysOnline.ACCESS_TYPE not in", values, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ACCESS_TYPE between", value1, value2, "accessType");
            return (Criteria) this;
        }

        public Criteria andAccessTypeNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ACCESS_TYPE not between", value1, value2, "accessType");
            return (Criteria) this;
        }

        public Criteria andSsoTokenIsNull() {
            addCriterion("jngSysOnline.SSO_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andSsoTokenIsNotNull() {
            addCriterion("jngSysOnline.SSO_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andSsoTokenEqualTo(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN =", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenNotEqualTo(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN <>", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenGreaterThan(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN >", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN >=", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenLessThan(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN <", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN <=", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenLike(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN like", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenNotLike(String value) {
            addCriterion("jngSysOnline.SSO_TOKEN not like", value, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenIn(List<String> values) {
            addCriterion("jngSysOnline.SSO_TOKEN in", values, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenNotIn(List<String> values) {
            addCriterion("jngSysOnline.SSO_TOKEN not in", values, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenBetween(String value1, String value2) {
            addCriterion("jngSysOnline.SSO_TOKEN between", value1, value2, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSsoTokenNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.SSO_TOKEN not between", value1, value2, "ssoToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenIsNull() {
            addCriterion("jngSysOnline.SYSTEM_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andSystemTokenIsNotNull() {
            addCriterion("jngSysOnline.SYSTEM_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andSystemTokenEqualTo(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN =", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenNotEqualTo(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN <>", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenGreaterThan(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN >", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN >=", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenLessThan(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN <", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN <=", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenLike(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN like", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenNotLike(String value) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN not like", value, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenIn(List<String> values) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN in", values, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenNotIn(List<String> values) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN not in", values, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenBetween(String value1, String value2) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN between", value1, value2, "systemToken");
            return (Criteria) this;
        }

        public Criteria andSystemTokenNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.SYSTEM_TOKEN not between", value1, value2, "systemToken");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIsNull() {
            addCriterion("jngSysOnline.ONLINE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIsNotNull() {
            addCriterion("jngSysOnline.ONLINE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS =", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS <>", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusGreaterThan(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS >", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusGreaterThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS >=", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLessThan(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS <", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLessThanOrEqualTo(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS <=", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLike(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS like", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotLike(String value) {
            addCriterion("jngSysOnline.ONLINE_STATUS not like", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_STATUS in", values, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotIn(List<String> values) {
            addCriterion("jngSysOnline.ONLINE_STATUS not in", values, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_STATUS between", value1, value2, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotBetween(String value1, String value2) {
            addCriterion("jngSysOnline.ONLINE_STATUS not between", value1, value2, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNull() {
            addCriterion("jngSysOnline.REG_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNotNull() {
            addCriterion("jngSysOnline.REG_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegDateEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE =", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE <>", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThan(Date value) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE >", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE >=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThan(Date value) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE <", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE <=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE not in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jngSysOnline.REG_DATE not between", value1, value2, "regDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JNG_SYS_ONLINE_LIST
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}